src/Comodin/urls.py
from django.conf.urls import url

from .views import  (
                    index,
                    clientes,
                    ComodinCreate,
                    ProveedorDetail,
                    ProveedorUpdate,
                    ClienteDetail,
                    ClienteUpdate,
                    ClienteCreate,
                    saldo_por_fechas
                    )


urlpatterns = [
    url(r'^proveedores/$', index, name='index'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^proveedores/crear/$',ComodinCreate.as_view(),name='comodinCreate'),
    url(r'^clientes/crear/$',ClienteCreate.as_view(),name='clientesCreate'),
    url(r'^proveedores/(?P<pk>\d+)/detallesProveedor/$', ProveedorDetail.as_view(),name='detallesProveedor'),
    url(r'^proveedores/(?P<pk>\d+)/editarProveedor/', ProveedorUpdate.as_view(), name='editarProveedor'),
    url(r'^clientes/(?P<pk>\d+)/detallesCliente/$', ClienteDetail.as_view(),name='detallesCliente'),
    url(r'^clientes/(?P<pk>\d+)/editarCliente/', ClienteUpdate.as_view(), name='editarCliente'),
    url(r'^clientes/facturas_cliente/$', saldo_por_fechas, name='facturas_cliente')
]

src/src/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin

from Comodin.views import (
            ComodinCreate,
            MarcaCreate,
            ClienteCreate,
            filtroP
            )

urlpatterns = [
    #Esta es la url de admin.
    url(r'^880e0d76/', admin.site.urls),
    url(r'^empleados/', include('Usuario.urls', namespace='Usuario')),
    url(r'^agencia/', include('Agencia.urls', namespace='Agencia')),
    url(r'^transacciones/', include('Transacciones.urls', namespace='Transacciones')),
    url(r'^registro/','Usuario.views.registro', name='registro'),
    url(r'^empresa/',include('Comodin.urls', namespace='index')),
    url(r'^finanzas/','Planillas.views.finanzas', name= 'finanzas'),
    # url(r'^clientes/$','Comodin.views.clientes', name='clientes'),
    url(r'^marca/',MarcaCreate.as_view(), name = 'marca'),
    url(r'^filtro/',filtroP,name = 'filtroP'),
    url(r'^productos/', include('Producto.urls', namespace= 'Producto')),
    url(r'^trans/','Transacciones.views.trans',name="trans"),
    url(r'^$','Usuario.views.inicio',name="base"),
    url(r'^logout/$', 'Usuario.views.cerrar', name='cerrar'),
    url(r'^filtro_m/$', 'Localizaciones.views.BusquedaMunicipio', name='filtro_municipio')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else:
    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

src/Comodin/models.py
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator, MinValueValidator

from django.db import models

# Create your models here.

class Comodin(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 45, blank = False, null = True)
    empresa = models.CharField(max_length = 45, blank = False, null = True)
    direccion = models.CharField(max_length = 45, blank = False, null = True)
    telefono = models.CharField(max_length = 8)
    nit = models.CharField(max_length = 20, blank = False, null = True)
    #False: Cliente, True: Proveedor.
    tipo = models.BooleanField()
    bloqueado = models.BooleanField(default = False)
    saldo = models.FloatField(null=True,blank=True,validators=[MinValueValidator(0)])

    municipio = models.ForeignKey('Localizaciones.Municipio')

    def __unicode__(self):
        return self.nombre + "--" + self.empresa

class Marca(models.Model):
    id = models.AutoField(primary_key = True)
    marca = models.CharField(max_length = 45)

    Comodin_id = models.ForeignKey('Comodin')

    def __unicode__(self):
        return str(self.marca)

src/Comodin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView, ListView

from .models import Comodin, Marca
from Transacciones.models import Factura
from Localizaciones.models import Departamento

#Lista de proveedores
@login_required(login_url='base')
def index(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    comodin = Comodin.objects.all().filter(tipo = True)

    context = {
        'comodin': comodin,
    }

    return render(request, 'comodin/proveedor_list.html', context)

def clientes(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    comodin = Comodin.objects.all().filter(tipo = False)

    context = {
        'comodin': comodin,
    }

    return render(request, 'comodin/clientes_list.html', context)

class ComodinCreate(CreateView):
    model = Comodin
    template_name = 'comodin/comodin_create.html'
    success_url = '/empresa/proveedores'

    fields = [
        'nombre',
        'empresa',
        'empresa',
        'direccion',
        'municipio',
        'telefono',
        'nit',
        'saldo',
        ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ComodinCreate, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        p = form.save(commit = False)

        p.tipo = True

        self.object = p.save()

        return super(ComodinCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ComodinCreate, self).get_context_data(**kwargs)

        departamentos = Departamento.objects.all()

        context.update({
            'departamentos': departamentos
        })

        return context

# ----------------------- clientes
class ClienteCreate(CreateView):
    model = Comodin
    template_name = 'comodin/comodin_create.html'
    success_url = '/empresa/clientes'

    fields = [
        'nombre',
        'empresa',
        'empresa',
        'direccion',
        'municipio',
        'telefono',
        'nit',
        'saldo',
        ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ClienteCreate, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        p = form.save(commit = False)

        p.tipo = False

        self.object = p.save()

        return super(ClienteCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ClienteCreate, self).get_context_data(**kwargs)

        departamentos = Departamento.objects.all()

        context.update({
            'departamentos': departamentos
        })

        return context


class ClienteDetail(DetailView):
    model = Comodin
    template_name = 'comodin/clientes_detail.html'

    # def get_queryset(self):
    #     self.agencia = get_object_or_404(Agencia, id=self.args[0])
    #     return Empleado.objects.filter(agencia=self.agencia)

    def get_context_data(self, **kwargs):
        context = super(ClienteDetail, self).get_context_data(**kwargs)
        context.update({'clientes' : Comodin.objects.all()}) #['empleados'] = Empleado.objects.all()
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ClienteDetail, self).dispatch(request, *args, **kwargs)

class ClienteUpdate(UpdateView):
    model = Comodin
    template_name = 'comodin/clientes_edit.html'
    success_url = reverse_lazy('index:clientes')

    fields = [

        'nombre',
        'empresa',
        'direccion',
        'telefono',
        'nit',
        'bloqueado',
        'municipio'

    ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ClienteUpdate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ClienteUpdate, self).get_context_data(**kwargs)

        departamentos = Departamento.objects.all()

        context.update({
            'departamentos': departamentos
        })

        return context

#---------------------------Marca
class MarcaCreate(CreateView):
    model = Marca
    template_name = 'comodin/marca_create.html'
    success_url = '/marca'

    fields = ['marca']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(MarcaCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

       context = super(MarcaCreate, self).get_context_data(**kwargs)
       proveedores = Comodin.objects.filter(tipo = True)

       context.update({
            "proveedores": proveedores,
       })

       return context

    def form_valid(self, form):

        m = form.save(commit = False)
        vID = self.request.POST['proveedor_id']

        vID = Comodin.objects.get(id=vID)

        print vID

        m.Comodin_id = vID

        self.object = m.save()

        return super(MarcaCreate, self).form_valid(form)
#------------------------------ proveedores
class ComodinProveedorList(ListView):
    model = Comodin
    context_object_name = "comodin_list"
    template_name = "comodin/proveedor_list.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ComodinProveedorList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        valor = 0
        for key, value in self.kwargs.iteritems():
            valor = value

        self.comodin = get_object_or_404(Comodin, nombre__iexact = Comodin.objects.get(id=valor))
        return Comodin.objects.filter(tipo=True)

class ProveedorDetail(DetailView):
    model = Comodin
    template_name = 'comodin/proveedor_detail.html'

    # def get_queryset(self):
    #     self.agencia = get_object_or_404(Agencia, id=self.args[0])
    #     return Empleado.objects.filter(agencia=self.agencia)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ProveedorDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProveedorDetail, self).get_context_data(**kwargs)
        context.update({'proveedores' : Comodin.objects.all()}) #['empleados'] = Empleado.objects.all()
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProveedorDetail, self).dispatch(request, *args, **kwargs)

class ProveedorUpdate(UpdateView):
    model = Comodin
    template_name = 'comodin/proveedor_edit.html'
    success_url = reverse_lazy('index:index')

    fields = [

        'nombre',
        'empresa',
        'direccion',
        'telefono',
        'nit',
        'bloqueado',
        'municipio',

    ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(ProveedorUpdate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProveedorUpdate, self).get_context_data(**kwargs)

        departamentos = Departamento.objects.all()

        context.update({
            'departamentos': departamentos
        })

        return context

@login_required(login_url='base')
def filtroP(request):
    proveedores = Comodin.objects.filter(tipo=False)
    print proveedores
    data = serializers.serialize('json', proveedores, fields = ('marca'))

    return HttpResponse(data, content_type = 'application/json')

@login_required(login_url='base')
def saldo_por_fechas(request):
    fecha_desde = request.GET['desde_anio']+'-'+request.GET['desde_mes']+'-'+request.GET['desde_dia']
    fecha_hasta = request.GET['hasta_anio']+'-'+request.GET['hasta_mes']+'-'+request.GET['hasta_dia']

    compras = Factura.objects.filter(
                    Comodin_id__id=request.GET['id'],
                    fecha__range=(fecha_desde, fecha_hasta)
                    )

    data = serializers.serialize('json', compras)

    return HttpResponse(data, content_type='application/json')

src/templates/comodin/clientes_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>Cliente {{comodin.nombre}}, ID: {{comodin.id}}</h2>

  <div class = "listados">
    <table class = "table">
      <tr>
        <td><strong>Nombre</td>
        <td>{{comodin.nombre}}</td>
      </tr>
      <tr>
        <td><strong>Bloqueado</td>
        <td>
          {% if comodin.bloqueado %}
          Si
          {% else %}
          No
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><strong>NIT</td>
        <td>{{comodin.nit}}</td>
      </tr>
      <tr>
        <td><strong>Empresa</td>
        <td>{{comodin.empresa}}</td>
      </tr>
      <tr>
        <td><strong>Dirección</td>
          <td>{{comodin.direccion}}, {{comodin.municipio}}, {{comodin.municipio.Departamento_id}}<td>
      </tr>
      <tr>
        <td><strong>Telefono</td>
        <td>{{comodin.telefono}}<td>
      </tr>
      <tr>
        <td><strong>Saldo</td>
        <td>{{comodin.saldo}}</td>
      </tr>

    </table>

    <h3>Venta total</h3>
    <label for="DESDE">Desde</label>
    <div id="DESDE" class="filtro">

      <div id="filtroForms">
        <div class = "encabezadoForms">
          <table class = "table">
            <tr>
              <td><label for="desde_a">Año</label></td>
              <td>
                <select id="anio" class="" name="desde_a">
                  <option value="0" selected>----</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><label for="desde_m">Mes</label></td>
              <td>
                <select id="mes" data-code="" name="desde_m">
                  <option value="0" selected>----</option>
                  <option value="1" >Enero</option>
                  <option value="2" >Febrero</option>
                  <option value="3" >Marzo</option>
                  <option value="4" >Abril</option>
                  <option value="5" >Mayo</option>
                  <option value="6" >Junio</option>
                  <option value="7" >Julio</option>
                  <option value="8" >Agosto</option>
                  <option value="9" >Septiembre</option>
                  <option value="10" >Octubre</option>
                  <option value="11" >Noviembre</option>
                  <option value="12" >Diciembre</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><label for="desde_d">Día</label></td>
              <td>
                <select id="dia" class="" name="desde_d">
                  <option value="0" selected>----</option>
                </select>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>

    <label for="HASTA">Hasta</label>
    <div id="HASTA" class="filtro">

      <div id="filtroForms">
        <div class = "encabezadoForms">
          <table class = "table">
            <tr>
              <td><label for="hasta_a">Año</label></td>
              <td>
                <select id="anio1" class="" name="hasta_a">
                  <option value="0">----</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><label for="hasta_m">Mes</label></td>
              <td>
                <select id="mes1" data-code="1" name="hasta_m">
                  <option value="0" selected>----</option>
                  <option value="1" >Enero</option>
                  <option value="2" >Febrero</option>
                  <option value="3" >Marzo</option>
                  <option value="4" >Abril</option>
                  <option value="5" >Mayo</option>
                  <option value="6" >Junio</option>
                  <option value="7" >Julio</option>
                  <option value="8" >Agosto</option>
                  <option value="9" >Septiembre</option>
                  <option value="10" >Octubre</option>
                  <option value="11" >Noviembre</option>
                  <option value="12" >Diciembre</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><label for="hasta_d">Día</label></td>
              <td>
                <select id="dia1" class="" name="hasta_d">
                  <option value="0" selected>----</option>
                </select>
              </td>
            </tr>
          </table>
        </div>
      </div>

    </div>
    <input type="button" id="filtro_fecha" name="filro_fecha" value="Buscar">
  <br></br>
    <h3>La venta total fue de: </h3><p id="saldo_total"></p>
  </div>

{% endblock %}

{% block js %}
<script type="text/javascript">

  $('#filtro_fecha').on('click', function(){

    var desde_anio = $("#anio").val();
    var desde_mes = $("#mes").val();
    var desde_dia = $("#dia").val();

    var hasta_anio = $("#anio1").val();
    var hasta_mes = $("#mes1").val();
    var hasta_dia = $("#dia1").val();



    $.ajax({

      data: {
        'desde_anio': desde_anio,
        'desde_mes': desde_mes,
        'desde_dia': desde_dia,
        'hasta_anio': hasta_anio,
        'hasta_mes': hasta_mes,
        'hasta_dia': hasta_dia,
        'id': {{comodin.id}}
      },
      url: "{% url 'index:facturas_cliente' %}",
      type: 'get',
      dataType: 'json',
      success: function(data){
        var total = 0;
        for (var i = 0; i < data.length; i++) {
          total += data[i].fields.precioTotal;
        }
        $('#saldo_total').text('Q.'+total);
      },
      error: function(){
        alert('Ocurrió un error en el servidor.');
      }

    });

  })

  $('#mes').on('change', calcular);
  $('#mes1').on('change', calcular);
  $('#document').ready(function(){
    var ahora = new Date();
    // var dia = ahora.getDate();
    // var mes = ahora.getMonth();
    var anio = ahora.getYear();
    if (anio < 2000)
         anio += 1900;
    var comboA = document.getElementById('anio');
    var comboB = document.getElementById('anio1');
    for(var i=anio; i>2015; i--){
      var option = document.createElement('option');
      option.value = i;
      option.innerHTML = i;
      comboA.options.add(option);
      option = document.createElement('option');
      option.value = i;
      option.innerHTML = i;
      comboB.options.add(option);
    }
  })

  function calcular(){
    var id = $(this).val();
    var code = $(this)[0].dataset.code;
    console.log(code);
    var anio = $('#anio'+code).val();
    var dias = cuantosDias(id, anio);
    var comboD = document.getElementById('dia'+code);
    comboD.length = 0;
    var p = document.createElement('option');
    p.value = '0';
    p.innerHTML = '------';
    comboD.options.add(p);
    for(var i = 1; i<=dias; i++){
      var option = document.createElement('option');
      option.value = i;
      option.innerHTML = i;
      comboD.options.add(option);
    }
  }

  function cuantosDias(mes, anyo){
    var cuantosDias = 31;
    if (mes == "4" || mes == "6" || mes == "7" || mes == "11")
      cuantosDias = 30;
    if (mes == "2" && (anyo/4) != Math.floor(anyo/4))
      cuantosDias = 28;
    if (mes == "2" && (anyo/4) == Math.floor(anyo/4))
      cuantosDias = 29;
    return cuantosDias;
  }
</script>
{% endblock %}

src/templates/comodin/clientes_edit.html
{% extends 'base.html' %}


{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Editar Cliente</h2>
      <label>Nombre</label>
        {{form.nombre}}
        <label>Empresa</label>
          {{form.empresa}}

          <label>Departamento</label>
          <select id="departamento" class="" name="departamento">
            <option value="0">--------</option>
            {% for departamento in departamentos %}
              <option value="{{departamento.id}}">{{departamento}}</option>
            {% endfor %}
          </select>

      <label>Municipio</label>
      {{form.municipio}}
      <label>Direccion</label>
        {{form.direccion}}
      <label>Telefono</label>
        {{form.telefono}}
        <label>NIT</label>
          {{form.nit}}
          <!-- <label>Bloqueado</label>
            {{form.bloqueado}} -->


      <input type='submit' value='Guardar'>
    </form>
  </div>
</div>

{% endblock %}

{% block js %}

<script type="text/javascript">
  $('#id_municipio').ready(function(){

    $('#id_municipio').empty();

  })

  $('#departamento').on('change', function(){

      $.ajax({

        data: {'id': $(this).val()},
        url: '/filtro_m',
        type: 'get',
        success: function(data){
          var municipios = document.getElementById('id_municipio');

          var vacio = document.createElement('option');
          vacio.value = '0';
          vacio.innerHTML = "------";

          municipios.options.add(vacio);

          for (var i = 0; i < data.length; i++) {
            var municipio = document.createElement('option');

            municipio.value = data[i].pk;

            municipio.innerHTML = data[i].fields.municipio;
            municipios.options.add(municipio)
          }
        }

      });

  })

</script>

{% endblock %}

src/templates/comodin/clientes_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<h2>Clientes</h2>

<div class = "divBotonesListado">
  <a href="/empresa/clientes/crear" class = "lnk" target="_blank">+</a>
  <a href="/empresa/clientes/crear" class = "descripcion"> Agregar</a>
</div>

<div class = "listados" >
  <div style="float: left">
  <table class = "table"   id = "tblDatos"  >
    <tr>
      <td><strong>Nombre</td>
      <td><strong>Empresa</td>
      <td><strong>Telefono</td>
      <td><strong>Saldo</td>
    </tr>


    {% for dato in comodin %}
      <tr id=datosTablaImprimir>
         <!--<td><a><input type = "checkbox" value = "Falso" id = {{dato.telefono}}  ></a></td>-->
        <td>{{dato.nombre}}</td>
        <td>{{dato.empresa}}</td>
        <td>{{dato.telefono}}</td>
        <td>{{dato.saldo}}</td>
        <td><a href={% url 'index:detallesCliente' dato.id %}><i>Ver</i></a></td>
        <td><a href={% url 'index:editarCliente' dato.id %}><i>Editar</i></a></td>
        <td><a><input type = "submit" value = "agregar" id = {{dato.telefono}}  onclick="nuevafila('impresion','{{dato.nombre}}','{{dato.empresa}}','{{dato.telefono}}','{{dato.saldo}}')" ></a></td>
        
      </tr>
    {% endfor %}

  </table>
  </div>
  
</div>

 

<div id="paginador"></div>

 <div style="float: left" >
    <table id=impresion class = "table" >
      <tr>
      <td><strong>Nombre</td>
      <td><strong>Empresa</td>
      <td><strong>Telefono</td>
      <td><strong>Saldo</td>
      <td><strong>Abono</td>
      </tr>
    </table>
  </div>


<input type=button value="Imprimir" onclick="imprimir('impresion')">

{% endblock %}

{% block js %}

<script type="text/javascript">
$(document).ready(function(){
  var p = new Paginador(
    document.getElementById('paginador'),
    document.getElementById('tblDatos'),
    10
  );

  p.Mostrar();
});


function nuevafila(idTabla,nombre,empresa,telefono,saldo){
  var tabla = document.getElementById(idTabla);
  var longitud = document.getElementById(idTabla).rows.length;
  var fila = tabla.insertRow(longitud);
  var cell1 = fila.insertCell(0);
  var cell2 = fila.insertCell(1);
  var cell3 = fila.insertCell(2);
  var cell4 = fila.insertCell(3);
  cell1.innerHTML = nombre;
  cell2.innerHTML = empresa;
  cell3.innerHTML = telefono;
  cell4.innerHTML = saldo;  
}





function imprimir(soloEsto){


var contenido = document.getElementById(soloEsto).outerHTML;
ventana=window.open("about :blank","ventana","width=700,height=600,top=0,left=3000");
ventana.document.open();
ventana.document.write('<html><link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css"/><head><title>METALUNA</title></head><body class="table" onprint="self.close()">');
ventana.document.write('<br></br><br></br><br></br><br></br><br></br><br>');
ventana.document.write('</body></html>');
ventana.document.write(contenido);
ventana.document.close();
ventana.print();
ventana.focus();
ventana.close();

}
</script>

{% endblock %}

src/templates/comodin/comodin_create.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Ingresar</h2>
      <label>Nombre</label>
        {{form.nombre}}
      <label>Empresa</label>
        {{form.empresa}}
      <label>Direccion</label>
        {{form.direccion}}

        <label>Departamento</label>
        <select id="departamento" class="" name="departamento">
          <option value="0">--------</option>
          {% for departamento in departamentos %}
            <option value="{{departamento.id}}">{{departamento}}</option>
          {% endfor %}
        </select>

      <label>Municipio</label>
        {{form.municipio}}
      <label>Telefono</label>
        {{form.telefono}}
      <label>NIT</label>
        {{form.nit}}
      <label>Saldo</label>
        {{form.saldo}}

      <input type='submit' value='Guardar'>
    </form>
  </div>
</div>

{% endblock %}

{% block js %}

<script type="text/javascript">
  $('#id_municipio').ready(function(){

    $('#id_municipio').empty();

  })

  $('#departamento').on('change', function(){

      $.ajax({

        data: {'id': $(this).val()},
        url: '/filtro_m',
        type: 'get',
        success: function(data){
          var municipios = document.getElementById('id_municipio');
          municipios.length = 0;

          var vacio = document.createElement('option');
          vacio.value = '0';
          vacio.innerHTML = "------";

          municipios.options.add(vacio);

          for (var i = 0; i < data.length; i++) {
            var municipio = document.createElement('option');

            municipio.value = data[i].pk;

            municipio.innerHTML = data[i].fields.municipio;
            municipios.options.add(municipio)
          }
        }

      });

  })

</script>

{% endblock %}

src/templates/comodin/marca_create.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Agregar Marca</h2>

      <label>Marca</label>
        {{form.marca}}

      <label>Proveedor</label>
      <a href="/empresa/proveedores/crear" class = "lnk" target="_blank">+</a>
      <select id = "proveedor_id" name = "proveedor">
        <option selected>------</option>
          {% for dato in proveedores %}
            <option value="{{dato.id}}">{{dato.empresa}}---{{dato.nombre}}</option>
          {% endfor %}
      </select>

      <input type='submit' value='Agregar'>
    </form>
  </div>
</div>

{% endblock %}

src/templates/comodin/proveedor_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Proveedores</h2>

<div class = "divBotonesListado">
  <a href="/empresa/proveedores/crear" class = "lnk" target="_blank">+</a>
  <a href="/empresa/proveedores/crear" class = "descripcion"> Agregar</a>
</div>


<div class = "listados">
  <table class = "table" id="tblDatos">
    <tr>
      <td><strong>Nombre</td>
      <td><strong>Empresa</td>
      <td><strong>Telefono</td>
        <td><strong>Saldo</td>
    </tr>

    {% for dato in comodin %}
      <tr>
        <td>{{dato.nombre}}</td>
        <td>{{dato.empresa}}</td>
        <td>{{dato.telefono}}</td>
        <td>{{dato.saldo}}</td>
        <td><a href={% url 'index:detallesProveedor' dato.id %}><i>Ver</i></a></td>
        <td><a href={% url 'index:editarProveedor' dato.id %}><i>Editar</i></a></td>
      </tr>
    {% endfor %}

  </table>
</div>
<div id="paginador"></div>

{% endblock %}

{% block js %}

<script type="text/javascript">
$(document).ready(function(){
  var p = new Paginador(
    document.getElementById('paginador'),
    document.getElementById('tblDatos'),
    15
  );

  p.Mostrar();
});
</script>

{% endblock %}