src/Agencia/urls.py
from django.conf.urls import url

from .views import (
                    agencia,
                    AgenciaDetail,
                    AgenciaEmpleadoList,
                    AgenciaProductoList,
                    index,
                    AgenciaUpdate,
                    VehiculoUpdate,
                    VehiculoDetail,
                    vehiculoList,
                    vehiculo,
                    EntregaUpdate,
                    entregaList,
                    EntregaDetail,
                    entrega,
                    mercaderia,
                    mercaderiaList,
                    MercaderiaDetail,
                    MercaderiaUpdate,
                    impresion,
                    )

urlpatterns = [

    #------Agencias-------------------------------
    url(r'^$', index, name='index'),
    url(r'^crear/', agencia, name='crear'),
    url(r'^(?P<pk>\d+)/detalles/$', AgenciaDetail.as_view(),name='detalles'),
    url(r'^(?P<pk>\d+)/detalles/empleados', AgenciaEmpleadoList.as_view(),name='detalles_empleado'),
    url(r'^(?P<pk>\d+)/detalles/productos', AgenciaProductoList.as_view(),name='detalles_producto'),
    url(r'^(?P<pk>\d+)/editar/', AgenciaUpdate.as_view(), name='editar'),
    #------Vehiculos------------------------------
    url(r'^vehiculo/(?P<pk>\d+)/detalle/',VehiculoDetail.as_view(), name='detail_v'),
    url(r'^vehiculo/(?P<pk>\d+)/editar/',VehiculoUpdate.as_view(),name='edit_v'),
    url(r'^vehiculo/$',vehiculoList, name = 'list_v'),
    url(r'^vehiculo/crear/',vehiculo, name = 'crear_v'),
    url(r'^vehiculo/impresion/',impresion, name = 'impresion_v'),
    #------Entregas-------------------------------1
    url(r'^entrega/crear/',entrega,name = 'crear_e'),
    url(r'^entrega/(?P<pk>\d+)/detalle/', EntregaDetail.as_view(), name='detail_e'),
    url(r'^entrega/(?P<pk>\d+)/editar/', EntregaUpdate.as_view(), name='edit_e'),
    url(r'^entrega/vehiculo/(?P<vehiculo_id>\d+)', entregaList, name='list_e'),
    #------Mercaderia-----------------------------
    url(r'^mercaderia/crear/', mercaderia, name = 'crear_m'),
    url(r'^mercaderia/(?P<pk>\d+)/detalle/', MercaderiaDetail.as_view(), name='detail_m'),
    url(r'^mercaderia/(?P<pk>\d+)/editar/', MercaderiaUpdate.as_view(), name='edit_m'),
    url(r'^mercaderia/$', mercaderiaList, name='list_m'),

]

src/Comodin/urls.py
from django.conf.urls import url

from .views import  (
                    index,
                    clientes,
                    ComodinCreate,
                    ProveedorDetail,
                    ProveedorUpdate,
                    ClienteDetail,
                    ClienteUpdate,
                    ClienteCreate,
                    saldo_por_fechas
                    )


urlpatterns = [
    url(r'^proveedores/$', index, name='index'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^proveedores/crear/$',ComodinCreate.as_view(),name='comodinCreate'),
    url(r'^clientes/crear/$',ClienteCreate.as_view(),name='clientesCreate'),
    url(r'^proveedores/(?P<pk>\d+)/detallesProveedor/$', ProveedorDetail.as_view(),name='detallesProveedor'),
    url(r'^proveedores/(?P<pk>\d+)/editarProveedor/', ProveedorUpdate.as_view(), name='editarProveedor'),
    url(r'^clientes/(?P<pk>\d+)/detallesCliente/$', ClienteDetail.as_view(),name='detallesCliente'),
    url(r'^clientes/(?P<pk>\d+)/editarCliente/', ClienteUpdate.as_view(), name='editarCliente'),
    url(r'^clientes/facturas_cliente/$', saldo_por_fechas, name='facturas_cliente')
]

src/src/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin

from Comodin.views import (
            ComodinCreate,
            MarcaCreate,
            ClienteCreate,
            filtroP
            )

urlpatterns = [
    #Esta es la url de admin.
    url(r'^880e0d76/', admin.site.urls),
    url(r'^empleados/', include('Usuario.urls', namespace='Usuario')),
    url(r'^agencia/', include('Agencia.urls', namespace='Agencia')),
    url(r'^transacciones/', include('Transacciones.urls', namespace='Transacciones')),
    url(r'^registro/','Usuario.views.registro', name='registro'),
    url(r'^empresa/',include('Comodin.urls', namespace='index')),
    url(r'^finanzas/','Planillas.views.finanzas', name= 'finanzas'),
    # url(r'^clientes/$','Comodin.views.clientes', name='clientes'),
    url(r'^marca/',MarcaCreate.as_view(), name = 'marca'),
    url(r'^filtro/',filtroP,name = 'filtroP'),
    url(r'^productos/', include('Producto.urls', namespace= 'Producto')),
    url(r'^trans/','Transacciones.views.trans',name="trans"),
    url(r'^$','Usuario.views.inicio',name="base"),
    url(r'^logout/$', 'Usuario.views.cerrar', name='cerrar'),
    url(r'^filtro_m/$', 'Localizaciones.views.BusquedaMunicipio', name='filtro_municipio')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else:
    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

src/templates/agencia_list.html
{% extends 'base.html' %}

{% block content %}

<div>
  {% for dato in agencias %}
    <label>Nombre</label>
    {{dato.nombre}}
    <label>Direccion</label>
    {{dato.direccion}}
    <label>Capital</label>
    {{dato.capital}}
    <label>Municipio</label>
    {{dato.Municipio_id}}
  {% endfor %}
</div>

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, maximum-scale=1">

<title>Metaluna</title>

<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>


<link href='{% static "css/bootstrap.css" %}' rel="stylesheet" type="text/css"/>

<link href='{% static "css/style.css" %}' rel="stylesheet" type="text/css"/>
<link href='{% static "css/font-awesome.css" %}' rel="stylesheet" type="text/css"/>
<link href='{% static "css/responsive.css" %}' rel="stylesheet" type="text/css" />
<link href='{% static "css/animate.css" %}' rel="stylesheet" type="text/css" />

<script type="text/javascript" src= '{% static "js/jquery.1.8.3.min.js" %}'></script>
<script type="text/javascript" src= '{% static "js/bootstrap.js" %}'></script>
<script type="text/javascript" src= '{% static "js/jquery-scrolltofixed.js" %}'></script>
<script type="text/javascript" src= '{% static "js/paginador.js" %}'></script>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src= '{% static "js/jquery.easing.1.3.js" %}'></script>
<script type="text/javascript" src= '{% static "js/jquery.isotope.js" %}'></script>
<script type="text/javascript" src= '{% static "js/wow.js" %}'></script>
<script type="text/javascript" src= '{% static "js/classie.js" %}'></script>

<!--[if lt IE 9]>
    <script src="js/respond-1.1.0.min.js"></script>
    <script src="js/html5shiv.js"></script>
    <script src="js/html5element.js"></script>
<![endif]-->


</head>

<body>
<div style="overflow:hidden;">
<header class="header" id="header"><!--header-start-->
	<div class="container">

					<a href="/"><img src="/static/img/logo.png"></a>

        <ul class="we-create animated fadeInUp delay-1s">
        	<li></li>
        </ul>
    </div>
	</header>
</div>


<nav class="main-nav-outer" id="test"><!--main-nav-start-->
	<div class="container">
        <ul class="main-nav">
        	<li><a href="/">Home</a></li>
						{% if user.is_staff %}
            <li><a href="/agencia">Agencias</a></li>
						{% endif %}
						<li><a href={% url 'Agencia:list_v' %}>Vehiculos</a></li>
            <li><a href="/productos">Productos</a></li>
            <li><a href="/transacciones">Transacciones</a></li>
						{% if user.is_staff %}
						<li><a href={% url 'index:index' %}>Proveedores</a></li>
            <li><a href={% url 'index:clientes' %}>Clientes</a></li>
						<li><a href=/finanzas>Finanzas</a></li>
						{% endif %}
            <!-- <li><a href="/planilla">Planillas</a></li> -->
            <!-- <li><a href="#contact">Usuarios</a></li> -->
        </ul>
        <a class="res-nav_click" href="#"><i class="fa-bars"></i></a>
    </div>
</nav><!--main-nav-end-->



<section class="main-section" id="service"><!--main-section-start-->
	<div class="container">

			{% block content %}
			{% endblock %}

	</div>
</section><!--main-section-end-->

	{% block arriba %}

	{% endblock %}





<footer class="footer">
    <div class="container">
			<span class="copyright"><a href="/logout">Cerrar Sesión</a></span>
				<span class="copyright">Copyright © 2016 | <a href="http://bootstraptaste.com/">Developed by Estigia</a></span>
    </div>
    <!--
        All links in the footer should remain intact.
        Licenseing information is available at: http://bootstraptaste.com/license/
        You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Knight
    -->
</footer>


<script type="text/javascript">
    $(document).ready(function(e) {
        $('#test').scrollToFixed();
        $('.res-nav_click').click(function(){
            $('.main-nav').slideToggle();
            return false
        });

    });
</script>

  <script>
    wow = new WOW(
      {
        animateClass: 'animated',
        offset:       100
      }
    );
    wow.init();

  </script>


<script type="text/javascript">
	$(window).load(function(){

		$('.main-nav li a').bind('click',function(event){
			var $anchor = $(this);

			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top - 102
			}, 1500,'easeInOutExpo');
			/*
			if you don't want to use the easing effects:
			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top
			}, 1000);
			*/
			event.preventDefault();
		});
	})
</script>

<script type="text/javascript">

$(window).load(function(){


  var $container = $('.portfolioContainer'),
      $body = $('body'),
      colW = 375,
      columns = null;


  $container.isotope({
    // disable window resizing
    resizable: true,
    masonry: {
      columnWidth: colW
    }
  });

  $(window).smartresize(function(){
    // check if columns has changed
    var currentColumns = Math.floor( ( $body.width() -30 ) / colW );
    if ( currentColumns !== columns ) {
      // set new column count
      columns = currentColumns;
      // apply width to container manually, then trigger relayout
      $container.width( columns * colW )
        .isotope('reLayout');
    }

  }).smartresize(); // trigger resize to set container width
  $('.portfolioFilter a').click(function(){
        $('.portfolioFilter .current').removeClass('current');
        $(this).addClass('current');

        var selector = $(this).attr('data-filter');
        $container.isotope({

            filter: selector,
         });
         return false;
    });

});

</script>

{% block js %}
{% endblock %}

</body>
</html>

src/templates/error.html
{% extends 'base.html' %}

{% block content %}
  
{% endblock %}

src/templates/index.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login Form</title>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <style>
      /* NOTE: The styles were added inline because Prefixfree needs access to your styles and they must be inlined if they are on local disk! */
      @import url(http://fonts.googleapis.com/css?family=Open+Sans);
.btn { display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 18px; color: #333333; text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#ffffff, endColorstr=#e6e6e6, GradientType=0); border-color: #e6e6e6 #e6e6e6 #e6e6e6; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); border: 1px solid #e6e6e6; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); cursor: pointer; *margin-left: .3em; }
.btn:hover, .btn:active, .btn.active, .btn.disabled, .btn[disabled] { background-color: #e6e6e6; }
.btn-large { padding: 9px 14px; font-size: 15px; line-height: normal; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; }
.btn:hover { color: #333333; text-decoration: none; background-color: #e6e6e6; background-position: 0 -15px; -webkit-transition: background-position 0.1s linear; -moz-transition: background-position 0.1s linear; -ms-transition: background-position 0.1s linear; -o-transition: background-position 0.1s linear; transition: background-position 0.1s linear; }
.btn-primary, .btn-primary:hover { text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25); color: #ffffff; }
.btn-primary.active { color: rgba(255, 255, 255, 0.75); }
.btn-primary { background-color: #4a77d4; background-image: -moz-linear-gradient(top, #6eb6de, #4a77d4); background-image: -ms-linear-gradient(top, #6eb6de, #4a77d4); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#6eb6de), to(#4a77d4)); background-image: -webkit-linear-gradient(top, #6eb6de, #4a77d4); background-image: -o-linear-gradient(top, #6eb6de, #4a77d4); background-image: linear-gradient(top, #6eb6de, #4a77d4); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#6eb6de, endColorstr=#4a77d4, GradientType=0);  border: 1px solid #3762bc; text-shadow: 1px 1px 1px rgba(0,0,0,0.4); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.5); }
.btn-primary:hover, .btn-primary:active, .btn-primary.active, .btn-primary.disabled, .btn-primary[disabled] { filter: none; background-color: #4a77d4; }
.btn-block { width: 100%; display:block; }

* { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; -ms-box-sizing:border-box; -o-box-sizing:border-box; box-sizing:border-box; }

html { width: 100%; height:100%; overflow:hidden; }

body { 
	width: 100%;
	height:100%;
	font-family: 'Open Sans', sans-serif;
	background: #092756;
	background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
}
.login { 
	position: absolute;
	top: 50%;
	left: 50%;
	margin: -150px 0 0 -150px;
	width:300px;
	height:300px;
}
.login h1 { color: #fff; text-shadow: 0 0 10px rgba(0,0,0,0.3); letter-spacing:1px; text-align:center; }

input { 
	width: 100%; 
	margin-bottom: 10px; 
	background: rgba(0,0,0,0.3);
	border: none;
	outline: none;
	padding: 10px;
	font-size: 13px;
	color: #fff;
	text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
	border: 1px solid rgba(0,0,0,0.3);
	border-radius: 4px;
	box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
	-webkit-transition: box-shadow .5s ease;
	-moz-transition: box-shadow .5s ease;
	-o-transition: box-shadow .5s ease;
	-ms-transition: box-shadow .5s ease;
	transition: box-shadow .5s ease;
}
input:focus { box-shadow: inset 0 -5px 45px rgba(100,100,100,0.4), 0 1px 1px rgba(255,255,255,0.2); }

    </style>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>

</head>

<body>
  <div class="login">
	<h1>Login</h1>
    <form method="post">
    	<input type="text" name="u" placeholder="Username" required="required" />
        <input type="password" name="p" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
</div>
  
    <script src="js/index.js"></script>

</body>
</html>

src/templates/sign-in.html

{% load staticfiles %}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Easy Admin Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href='{% static "cssLogin/css/bootstrap.min.css" %}' rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href='{% static "cssLogin/css/style.css" %}' rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href='{% static "cssLogin/css/font-awesome.css" %}' rel="stylesheet">
<!-- jQuery -->
<!-- lined-icons -->
<link rel="stylesheet" href='{% static "cssLogin/css/icon-font.min.css" %}' type='text/css' />
<!-- //lined-icons -->
<!-- chart -->
<script src='{% static "cssLogin/js/Chart.js" %}'></script>
<!-- //chart -->
<!--animate-->
<link href='{% static "cssLogin/css/animate.css" %}' rel="stylesheet" type="text/css" media="all">
<script src='{% static "cssLogin/js/wow.min.js" %'}></script>
	<script>
		 new WOW().init();
	</script>
<!--//end-animate-->
<!----webfonts--->
<link href='//fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<!---//webfonts--->
 <!-- Meters graphs -->
<script src='{% static "js/jquery-1.10.2.min.js" %}' ></script>
<!-- Placed js at the end of the document so the pages load faster -->

</head>

 <body class="sign-in-up">
    <section>
			<div id="page-wrapper" class="sign-in-wrapper">
				<div class="graphs">
					<div class="sign-in-form">
						<div class="sign-in-form-top">
							<p><span>Sign In </span></p>
						</div>
						<div class="signin">
							<div class="signin-rit">
								<!-- <span class="checkbox1"> -->
									 <!-- <label class="checkbox"><input type="checkbox" name="checkbox" checked="">Forgot Password ?</label> -->
								<!-- </span> -->

								<div class="clearfix"> </div>
							</div>
							<form method='post' action='' >
								{%csrf_token%}
								{{form.username}}
							<div class="log-input">
								<div class="log-input-left">

									<!-- <input type="text" class="user" value="Yourname" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email address:';}"/> -->
								</div>
								<span class="checkbox2">
									 <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i></label>
								</span>
								<div class="clearfix"> </div>
							</div>
							<div class="log-input">
								<div class="log-input-left">
									{{form.password}}
									 <!-- <input type="password" class="lock" value="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email address:';}"/> -->
								</div>
								<span class="checkbox2">
									 <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i></label>
								</span>
								<div class="clearfix"> </div>
							</div>
							<input type="submit" value="Login to your account">
						</form>
						</div>
						<div class="new_people">
							<!-- <h4>For New People</h4> -->
							<!-- <p>Having hands on experience in creating innovative designs,I do offer design -->
								<!-- solutions which harness.</p> -->
							<a href="sign-up.html">Register Now!</a>
						</div>
					</div>
				</div>
			</div>
		<!--footer section start-->
			<footer>
			   <p>&copy 2015 Easy Admin Panel. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">w3layouts.</a></p>
			</footer>
        <!--footer section end-->
	</section>

<script src='{% static "cssLogin/js/jquery.nicescroll.js" %}'></script>
<script src='{% static "cssLogin/js/scripts.js" %}'></script>
<!-- Bootstrap Core JavaScript -->
   <script src='{% static "cssLogin/js/bootstrap.min.js" %}'></script>
</body>
</html>