src/Agencia/urls.py
from django.conf.urls import url

from .views import (
                    agencia,
                    AgenciaDetail,
                    AgenciaEmpleadoList,
                    AgenciaProductoList,
                    index,
                    AgenciaUpdate,
                    VehiculoUpdate,
                    VehiculoDetail,
                    vehiculoList,
                    vehiculo,
                    EntregaUpdate,
                    entregaList,
                    EntregaDetail,
                    entrega,
                    mercaderia,
                    mercaderiaList,
                    MercaderiaDetail,
                    MercaderiaUpdate,
                    impresion,
                    )

urlpatterns = [

    #------Agencias-------------------------------
    url(r'^$', index, name='index'),
    url(r'^crear/', agencia, name='crear'),
    url(r'^(?P<pk>\d+)/detalles/$', AgenciaDetail.as_view(),name='detalles'),
    url(r'^(?P<pk>\d+)/detalles/empleados', AgenciaEmpleadoList.as_view(),name='detalles_empleado'),
    url(r'^(?P<pk>\d+)/detalles/productos', AgenciaProductoList.as_view(),name='detalles_producto'),
    url(r'^(?P<pk>\d+)/editar/', AgenciaUpdate.as_view(), name='editar'),
    #------Vehiculos------------------------------
    url(r'^vehiculo/(?P<pk>\d+)/detalle/',VehiculoDetail.as_view(), name='detail_v'),
    url(r'^vehiculo/(?P<pk>\d+)/editar/',VehiculoUpdate.as_view(),name='edit_v'),
    url(r'^vehiculo/$',vehiculoList, name = 'list_v'),
    url(r'^vehiculo/crear/',vehiculo, name = 'crear_v'),
    url(r'^vehiculo/impresion/',impresion, name = 'impresion_v'),
    #------Entregas-------------------------------1
    url(r'^entrega/crear/',entrega,name = 'crear_e'),
    url(r'^entrega/(?P<pk>\d+)/detalle/', EntregaDetail.as_view(), name='detail_e'),
    url(r'^entrega/(?P<pk>\d+)/editar/', EntregaUpdate.as_view(), name='edit_e'),
    url(r'^entrega/vehiculo/(?P<vehiculo_id>\d+)', entregaList, name='list_e'),
    #------Mercaderia-----------------------------
    url(r'^mercaderia/crear/', mercaderia, name = 'crear_m'),
    url(r'^mercaderia/(?P<pk>\d+)/detalle/', MercaderiaDetail.as_view(), name='detail_m'),
    url(r'^mercaderia/(?P<pk>\d+)/editar/', MercaderiaUpdate.as_view(), name='edit_m'),
    url(r'^mercaderia/$', mercaderiaList, name='list_m'),

]

src/Producto/urls.py
from django.conf.urls import url

from .views import (
    index,
    ProductoDetail,
    ProductoUpdate,
    producto,
    filtroProducto,
    lote,
    tipo_producto,
    calibre,
    forma,
    longitud,
    material,
    existencias
)

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'crear$', producto, name = 'crear'),
    url(r'(?P<pk>\d+)$',ProductoDetail.as_view(), name='detail'),
    url(r'(?P<pk>\d+)/editar',ProductoUpdate.as_view(), name='edit'),
    url(r'filtroProducto/', filtroProducto, name='filtroProducto'),
    url(r'^existencias/', existencias, name='existencias'),
    url(r'crear_lote', lote, name = 'lote'),
    url(r'tipoproducto', tipo_producto, name = 'tipo_producto'),
    url(r'crear_forma', forma, name = 'forma'),
    url(r'crear_calibre', calibre, name = 'calibre'),
    url(r'crear_longitud', longitud, name = 'longitud'),
    url(r'crear_material', material, name = 'material'),
]

src/src/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin

from Comodin.views import (
            ComodinCreate,
            MarcaCreate,
            ClienteCreate,
            filtroP
            )

urlpatterns = [
    #Esta es la url de admin.
    url(r'^880e0d76/', admin.site.urls),
    url(r'^empleados/', include('Usuario.urls', namespace='Usuario')),
    url(r'^agencia/', include('Agencia.urls', namespace='Agencia')),
    url(r'^transacciones/', include('Transacciones.urls', namespace='Transacciones')),
    url(r'^registro/','Usuario.views.registro', name='registro'),
    url(r'^empresa/',include('Comodin.urls', namespace='index')),
    url(r'^finanzas/','Planillas.views.finanzas', name= 'finanzas'),
    # url(r'^clientes/$','Comodin.views.clientes', name='clientes'),
    url(r'^marca/',MarcaCreate.as_view(), name = 'marca'),
    url(r'^filtro/',filtroP,name = 'filtroP'),
    url(r'^productos/', include('Producto.urls', namespace= 'Producto')),
    url(r'^trans/','Transacciones.views.trans',name="trans"),
    url(r'^$','Usuario.views.inicio',name="base"),
    url(r'^logout/$', 'Usuario.views.cerrar', name='cerrar'),
    url(r'^filtro_m/$', 'Localizaciones.views.BusquedaMunicipio', name='filtro_municipio')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else:
    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

src/Agencia/models.py
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator, MinValueValidator

from django.db import models

# Create your models here.

class Agencia(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 30, blank = True, null = True)
    direccion = models.CharField(max_length = 45)
    capital = models.FloatField(null=True,blank=True,validators=[MinValueValidator(0)])
    Municipio_id = models.ForeignKey('Localizaciones.Municipio')

    def __unicode__(self):
        return self.nombre


class Vehiculo(models.Model):
    id = models.AutoField(primary_key = True)
    marca = models.CharField(max_length = 20, blank = True, null = True)
    modelo = models.IntegerField(blank = True, null = True)
    placa = models.CharField(max_length = 7, blank = True, null = True)
    Agencia_id = models.ForeignKey('Agencia')

    def __unicode__(self):
        return self.placa


class Entrega(models.Model):
    id = models.AutoField(primary_key = True)
    kEntrada = models.FloatField()
    kSalida = models.FloatField()
    fecha = models.DateTimeField()
    vale = models.IntegerField(blank = True, null = True)
    Vehiculo_id = models.ForeignKey('Vehiculo')

    def __unicode__(self):
        return str(self.id)

    def kTotal(self):
        return self.kEntrada - self.kSalida


class Mercaderia(models.Model):
    id = models.AutoField(primary_key = True)
    Producto_id = models.ForeignKey('Producto.Producto')
    Agencia_id = models.ForeignKey('Agencia')
    cantidad = models.IntegerField(blank = True, null = True)

    def __unicode__(self):
        return str(self.Producto_id)

src/Agencia/forms.py
from django import forms
from .models import Agencia, Vehiculo, Entrega, Mercaderia

class AgenciaForm(forms.ModelForm):
    class Meta:
        model = Agencia
        fields = ["nombre", "direccion", "capital", "Municipio_id"]

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ["marca", "modelo", "placa", "Agencia_id"]

class EntregaForm(forms.ModelForm):
    class Meta:
        model = Entrega
        fields = ["kEntrada", "kSalida", "fecha", "vale", "Vehiculo_id"]

class MercaderiaForm(forms.ModelForm):
    class Meta:
        model = Mercaderia
        fields = ["Producto_id", "Agencia_id", "cantidad"]

src/Agencia/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.views.generic.edit import UpdateView
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, ListView

from .models import Agencia, Vehiculo, Entrega, Mercaderia
from .forms import AgenciaForm, VehiculoForm, EntregaForm, MercaderiaForm
from Usuario.models import Empleado

#Vistas de Agencia y detalles---------------------------------
@login_required(login_url='base')
def agencia(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    form = AgenciaForm(request.POST or None)

    context = {"form":form}

    if form.is_valid():
        form.save()
        return redirect("Agencia:index")

    return render(request, "agencia/agencia.html", context)

class AgenciaDetail(DetailView):
    model = Agencia
    template_name = 'agencia/agencia_detail.html'

    # def get_queryset(self):
    #     self.agencia = get_object_or_404(Agencia, id=self.args[0])
    #     return Empleado.objects.filter(agencia=self.agencia)

    def get_context_data(self, **kwargs):
        context = super(AgenciaDetail, self).get_context_data(**kwargs)
        context.update({'empleados' : Empleado.objects.all()}) #['empleados'] = Empleado.objects.all()
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(AgenciaDetail, self).dispatch(request, *args, **kwargs)

@login_required(login_url='base')
def index(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    agencias = Agencia.objects.all()

    context = {
        'agencias': agencias,
    }

    return render(request, 'agencia/agencia_list.html', context)

class AgenciaEmpleadoList(ListView):
    model = Agencia
    context_object_name = "empleados_list"
    template_name = "agencia/empleados_por_agencia.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(AgenciaEmpleadoList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        valor = 0
        for key, value in self.kwargs.iteritems():
            valor = value

        #self.agencia = get_object_or_404(Agencia, nombre__iexact = Agencia.objects.get(id=valor))
        self.agencia = Agencia.objects.get(id=valor)
        return Empleado.objects.filter(Agencia_id=self.agencia.id)
    #
    # def get_context_data(self, **kwargs):
    #     print kwargs
    #     print kwargs
    #     print kwargs
    #     print kwargs
    #     context = super(AgenciaEmpleadoList, self).get_context_data(**kwargs)
    #     #context.update({'agencia' : Agencia.objects.get(id=valor)})
    #     return context
    #

class AgenciaProductoList(ListView):
    model = Agencia
    context_object_name = "productos_list"
    template_name = "agencia/productos_por_agencia.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(AgenciaProductoList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        valor = 0
        for key, value in self.kwargs.iteritems():
            valor = value

        self.agencia = Agencia.objects.get(id=valor)
        #get_object_or_404(Agencia, nombre__iexact = Agencia.objects.get(id=valor))
        return Mercaderia.objects.filter(Agencia_id=self.agencia.id)

class AgenciaUpdate(UpdateView):
    model = Agencia
    template_name = 'agencia/agencia_edit.html'
    success_url = reverse_lazy('Agencia:index')

    fields = [

        'nombre',
        'direccion',
        'capital',
        'Municipio_id',

    ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')

        return super(AgenciaUpdate, self).dispatch(request, *args, **kwargs)

#-------------------------------------------------------------
#Vistas de Vehiculos------------------------------------------
@login_required(login_url='base')
def vehiculo(request):
    form = VehiculoForm(request.POST or None)

    context = {"form": form}

    if form.is_valid():
        form.save()

        return redirect("Agencia:list_v")

    return render(request, "agencia/vehiculo.html", context)

class VehiculoDetail(DetailView):
    model = Vehiculo
    template_name = 'agencia/vehiculo_detail.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(VehiculoDetail, self).dispatch(request, *args, **kwargs)

class VehiculoUpdate(UpdateView):
    model = Vehiculo
    template_name = 'agencia/vehiculo_edit.html'
    success_url = reverse_lazy('Agencia:list_v')

    fields = [

        'marca',
        'modelo',
        'placa',
        'Agencia_id',

    ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(VehiculoUpdate, self).dispatch(request, *args, **kwargs)

@login_required(login_url='base')
def vehiculoList(request):
    vehiculos = Vehiculo.objects.all()

    context = {
        'vehiculos': vehiculos,
    }

    return render(request,'agencia/vehiculo_list.html', context)

#-------------------------------------------------------------
#Vistas de Entrega--------------------------------------------
@login_required(login_url='base')
def entrega(request):
    form = EntregaForm(request.POST or None, initial={'fecha': timezone.now()})

    context = {"form": form}

    if form.is_valid():
        form.save()
        return redirect("Agencia:list_v")
        #aca agregue el form save
    else:
        print "popo"

    return render(request, "agencia/entrega.html", context)

@login_required(login_url='base')
def entregaList(request, vehiculo_id):
    entregas = Entrega.objects.filter(Vehiculo_id = vehiculo_id)

    context = {
        'entregas': entregas,
    }

    return render(request, 'agencia/entrega_list.html', context)

class EntregaDetail(DetailView):
    model = Entrega
    template_name = 'agencia/entrega_detail.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EntregaDetail, self).dispatch(request, *args, **kwargs)

class EntregaUpdate(UpdateView):
    model = Entrega
    template_name = 'agencia/entrega_edit.html'
    success_url = reverse_lazy('Agencia:list_v')

    fields = [
        'kEntrada',
        'kSalida',
        'fecha',
        'vale',
        'Vehiculo_id',
    ]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EntregaUpdate, self).dispatch(request, *args, **kwargs)
#-------------------------------------------------------------
#Vistas de Mercaderia-----------------------------------------
@login_required(login_url='base')
def mercaderia(request):
    form = MercaderiaForm()

    context = {"form": form}

    return render(request, "agencia/mercaderia.html", context)

@login_required(login_url='base')
def mercaderiaList(request):
    mercaderia = Mercaderia.objects.all()

    context = {
        'mercaderia': mercaderia,
    }

    return render(request, 'agencia/mercaderia_list.html', context)

class MercaderiaDetail(DetailView):
    model = Mercaderia
    template_name = 'agencia/mercaderia_detail.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MercaderiaDetail, self).dispatch(request, *args, **kwargs)

class MercaderiaUpdate(UpdateView):
    model = Mercaderia
    template_name = 'agencia/mercaderia_edit.html'
    success_url = reverse_lazy('Agencia:list_m')

    fields = [
        'Producto_id',
        'Agencia_id',
        'cantidad',
    ]
def impresion(request):
    vehiculos = Vehiculo.objects.all()

    context = {
        'vehiculos': vehiculos,
    }
    return render(request, "agencia/impresionEntrega.html",context)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MercaderiaUpdate, self).dispatch(request, *args, **kwargs)
#-----------------------------------------------------------

src/templates/agencia/agencia.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}

      <h2>Crear Agencia</h2>
      <label>Nombre</label>
        {{form.nombre}}
      <label>Dirección</label>
        {{form.direccion}}
      <label>Capital</label>
        {{form.capital}}
      <label>Municipio</label>
        {{form.Municipio_id}}

      <input type='submit' value='Guardar'>
    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/agencia_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>Agencia {{agencia.nombre}}</h2>

  <div class = "listados">


    <table class = "table">
      <tr>
        <td><strong>Dirección</td>
          <td>{{agencia.direccion}}<td>
      </tr>
      <tr>
        <td><strong>Capital</td>
        <td>{{agencia.capital}}<td>
      </tr>
      <tr>
        <td><strong>Municipio</td>
        <td>{{agencia.Municipio_id}}</td>
      </tr>
    </table>

  </div>

{% endblock %}

src/templates/agencia/entrega.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}

      <h2>Agregar Entrega</h2>
      <label>Kilometraje de Entrada</label>
        {{form.kEntrada}}
      <label>Kilometraje de Salida</label>
        {{form.kSalida}}
      <label>Fecha</label>
        {{form.fecha}}
      <label>Vale</label>
        {{form.vale}}
      <label>Vehiculo</label>
        {{form.Vehiculo_id}}

      <input type='submit' value='Agregar'>

    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/entrega_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>Detalle de Entrega No. {{entrega.id}} </h2>
    <div class = "listados">

      <table class = "table">
        <tr>
          <td><strong>Kilometraje de salida</td>
          <td>{{entrega.kSalida}}<td>
        </tr>
        <tr>
          <td><strong>Kilometraje de entrada</td>
          <td>{{entrega.kEntrada}}<td>
        </tr>
        <tr>
          <td><strong>Fecha</td>
          <td>{{entrega.fecha}}</td>
        </tr>
        <tr>
          <td><strong>Vale</td>
          <td>{{entrega.vale}}</td>
        </tr>
        <tr>
          <td><strong>Vehiculo</td>
          <td>{{entrega.Vehiculo_id}}</td>
        </tr>
      </table>

    </div>
{% endblock %}

src/templates/agencia/entrega_edit.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Editar Entrega</h2>

      <label>Kilometraje de salida</label>
        {{form.kSalida}}
      <label>Kilometraje de entrada</label>
        {{form.kEntrada}}
      <label>Fecha</label>
        {{form.fecha}}
      <label>Vale</label>
        {{form.vale}}
      <label>Vehiculo</label>
        {{form.Vehiculo_id}}

      <input type='submit' value='Editar'>

    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/mercaderia.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Mercaderia</h2>

      <label>Producto</label>
        {{form.Producto_id}}
      <label>Agencia</label>
        {{form.Agencia_id}}
      <label>Cantidad</label>
        {{form.cantidad}}

      <input type='submit' value='Agregar'>
    </form> 
  </div>
</div>

{% endblock %}

src/templates/agencia/mercaderia_detail.html
{% extends 'base.html' %}

{% block content %}

  <h2>Detalle de Producto {{mercaderia.Producto_id}} </h2>
    <div class = "listados">
      <table class = "table">

        <tr>
          <td><strong>Producto</td>
          <td>{{mercaderia.Producto_id}}<td>
        </tr>
        <tr>
          <td><strong>Agencia</td>
          <td>{{mercaderia.Agencia_id}}<td>
        </tr>
        <tr>
          <td><strong>Cantidad</td>
          <td>{{mercaderia.cantidad}}</td>
        </tr>
      </table>
    </div>

{% endblock %}

src/templates/agencia/mercaderia_edit.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Editar Entrega</h2>

      <label>Producto</label>
        {{form.Producto_id}}</br>
      <label>Agencia</label>
        {{form.Agencia_id}}</br>
      <label>Cantidad</label>
        {{form.cantidad}}</br>

      <input type='submit' value='Editar'>

    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/mercaderia_list.html
{% extends 'base.html' %}

{% block content %}

  <h2>Mercaderia</h2>
  <div class = "listados">
    <table class = "table">

      <tr>
        <td><strong>Producto</td>
        <td><strong>Agencia</td>
        <td><strong>Cantidad</td>
      </tr>

      {% for dato in mercaderia %}
        <tr>
          <td>{{dato.Producto_id}}</td>
          <td>{{dato.Agencia_id}}</td>
          <td>{{dato.cantidad}}</td>
          <td><a href={% url 'Agencia:detail_m' dato.id %}><i>Ver</i></a></td>
          <td><a href={% url 'Agencia:edit_m' dato.id %}><i>Editar</i></a></td>
        </tr>
      {% endfor %}

    </table>
  </div>

{% endblock %}

src/templates/agencia/productos_por_agencia.html
{% extends 'base.html' %}

{% block content %}
  <h2>Productos de {{productos_list.first.Agencia_id}}</h2>

  <div class="submenu">
    <table class="table">
      <tr>
        <td>Descripcion</td>
        <td>Cantidad</td>
      </tr>
      {% for producto in productos_list %}
      <tr>
        <td>{{ producto }}</td>
        <td>{{ producto.cantidad }}</td>
        <td><a href={% url 'Producto:detail' producto.id %}><i>Ver</i></a></td>
        <td><a href={% url 'Producto:edit' producto.id %}><i>Editar</i></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

src/templates/agencia/vehiculo.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Agregar Vehiculo</h2>

      <label>Marca</label>
        {{form.marca}}<br/>
      <label>Modelo</label>
        {{form.modelo}}<br/>
      <label>Placa</label>
        {{form.placa}}<br/>
      <label>Agencia</label>
        {{form.Agencia_id}}<br/>

      <input type='submit' value='Agregar'>
    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/vehiculo_detail.html
{% extends 'base.html' %}

{% block content %}

  <h2>Vehiculo {{vehiculo.placa}} </h2>
    <div class = "listados">
      <table class = "table">
        <tr>
          <td><strong>Marca</td>
          <td>{{vehiculo.marca}}<td>
        </tr>
        <tr>
          <td><strong>Modelo</td>
          <td>{{vehiculo.modelo}}<td>
        </tr>
        <tr>
          <td><strong>Placa</td>
          <td>{{vehiculo.placa}}</td>
        </tr>
        <tr>
          <td><strong>Agencia a la que pertenece</td>
          <td>{{vehiculo.Agencia_id}}</td>
        </tr>
      </table>
    </div>
{% endblock %}

src/templates/agencia/vehiculo_edit.html
{% extends 'base.html' %}

{% block content %}

<div id="bloqueForms">
  <div class = "camposForms">
    <form method="post" action="">
      {%csrf_token%}
      <h2>Editar Vehiculo</h2>

      <label>Marca</label>
        {{form.marca}}
      <label>Modelo</label>
        {{form.modelo}}
      <label>Placa</label>
        {{form.placa}}
      <label>Agencia</label>
        {{form.Agencia_id}}

      <input type='submit' value='Editar'>
    </form>
  </div>
</div>

{% endblock %}

src/templates/agencia/vehiculo_list.html
{% extends 'base.html' %}

{% block content %}

  <h2>Vehiculos</h2>

  <div class = "divBotonesListado">
    <a href="/agencia/vehiculo/crear/" class = "lnk" target="_blank">+</a>
    <a href="/agencia/vehiculo/crear/" class = "descripcion"> Agregar &nbsp;&nbsp;&nbsp;</a>
    <a href="/agencia/vehiculo/impresion/" class = "lnk" target="_blank">+</a>
    <a href="/agencia/vehiculo/impresion/" class = "descripcion"> Imprimir Orden de Entrega</a>
  </div>


  <div class = "listados">
    <table class = "table" id="tblDatos">
      <tr>
        <td><strong>Marca</td>
        <td><strong>Modelo</td>
        <td><strong>Placa</td>
        <td><strong>Agencia</td>
      </tr>

      {% for dato in vehiculos %}
        <tr>
          <td>{{dato.marca}}</td>
          <td>{{dato.modelo}}</td>
          <td>{{dato.placa}}</td>
          <td>{{dato.Agencia_id}}</td>
          <td><a href={% url 'Agencia:detail_v' dato.id %}><i>Ver</i></a></td>
          <td><a href={% url 'Agencia:edit_v' dato.id %}><i>Editar</i></a></td>
          <td><a href={% url 'Agencia:list_e' dato.id %}><i>Entregas</i></a></td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div id="paginador"></div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){
  var p = new Paginador(
    document.getElementById('paginador'),
    document.getElementById('tblDatos'),
    15
  );

  p.Mostrar();
});
</script>
{% endblock %}