src/Comodin/urls.py
from django.conf.urls import url

from .views import  (
                    index,
                    clientes,
                    ComodinCreate,
                    ProveedorDetail,
                    ProveedorUpdate,
                    ClienteDetail,
                    ClienteUpdate,
                    ClienteCreate,
                    saldo_por_fechas
                    )


urlpatterns = [
    url(r'^proveedores/$', index, name='index'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^proveedores/crear/$',ComodinCreate.as_view(),name='comodinCreate'),
    url(r'^clientes/crear/$',ClienteCreate.as_view(),name='clientesCreate'),
    url(r'^proveedores/(?P<pk>\d+)/detallesProveedor/$', ProveedorDetail.as_view(),name='detallesProveedor'),
    url(r'^proveedores/(?P<pk>\d+)/editarProveedor/', ProveedorUpdate.as_view(), name='editarProveedor'),
    url(r'^clientes/(?P<pk>\d+)/detallesCliente/$', ClienteDetail.as_view(),name='detallesCliente'),
    url(r'^clientes/(?P<pk>\d+)/editarCliente/', ClienteUpdate.as_view(), name='editarCliente'),
    url(r'^clientes/facturas_cliente/$', saldo_por_fechas, name='facturas_cliente')
]

src/Producto/urls.py
from django.conf.urls import url

from .views import (
    index,
    ProductoDetail,
    ProductoUpdate,
    producto,
    filtroProducto,
    lote,
    tipo_producto,
    calibre,
    forma,
    longitud,
    material,
    existencias
)

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'crear$', producto, name = 'crear'),
    url(r'(?P<pk>\d+)$',ProductoDetail.as_view(), name='detail'),
    url(r'(?P<pk>\d+)/editar',ProductoUpdate.as_view(), name='edit'),
    url(r'filtroProducto/', filtroProducto, name='filtroProducto'),
    url(r'^existencias/', existencias, name='existencias'),
    url(r'crear_lote', lote, name = 'lote'),
    url(r'tipoproducto', tipo_producto, name = 'tipo_producto'),
    url(r'crear_forma', forma, name = 'forma'),
    url(r'crear_calibre', calibre, name = 'calibre'),
    url(r'crear_longitud', longitud, name = 'longitud'),
    url(r'crear_material', material, name = 'material'),
]

src/Transacciones/urls.py
from django.conf.urls import url

from .views import (
    ventas,
    compras,
    venta,
    compra,
    credito,
    facturaList,
    FacturaDetail,
    abonos,
    index,
    abonosList,
    AbonoDetail,
    creditoList,
    CreditoClienteDetail,
    CreditoProveedorDetail,
    anular
    #AbonoUpdate
    )


urlpatterns = [
    url(r'^ventas/$',ventas, name='ventas'),
    url(r'^compras/$', compras, name='compras'),
    url(r'^venta/', venta, name='venta'),
    url(r'^compra/', compra, name='compra'),
    url(r'^$', index, name='index'),
    url(r'^compras/crear_credito', credito, name='compra_credito'),
    url(r'^ventas/crear_credito', credito, name='venta_credito'),
    url(r'^(compras)/facturas', facturaList, name='facturas_compras'),
    url(r'^(ventas)/facturas', facturaList, name='facturas_ventas'),
    url(r'^facturas/(?P<pk>\d+)/detalles', FacturaDetail.as_view(), name='facturas'),
    url(r'^(compras)/abonos/crear', abonos, name='abonos'),
    url(r'^(compras)/abonos/$', abonosList, name='abonos_list'),
    url(r'^(ventas)/abonos/crear', abonos, name='abonos_v'),
    url(r'^(ventas)/abonos/$', abonosList, name='abonos_list_v'),
    url(r'^abonos/(?P<pk>\d+)/detalles', AbonoDetail.as_view(), name='abonos_detail'),
    url(r'^(compras)/creditos/$', creditoList, name='creditos_compras'),
    url(r'^(ventas)/creditos/$', creditoList, name='creditos_ventas'),
    url(r'^compras/creditos/(?P<pk>\d+)/detalles', CreditoProveedorDetail.as_view(), name='creditoPDetail'),
    url(r'^ventas/creditos/(?P<pk>\d+)/detalles', CreditoClienteDetail.as_view(), name='creditoCDetail'),
    url(r'^anular/', anular, name='anular')
]

src/src/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin

from Comodin.views import (
            ComodinCreate,
            MarcaCreate,
            ClienteCreate,
            filtroP
            )

urlpatterns = [
    #Esta es la url de admin.
    url(r'^880e0d76/', admin.site.urls),
    url(r'^empleados/', include('Usuario.urls', namespace='Usuario')),
    url(r'^agencia/', include('Agencia.urls', namespace='Agencia')),
    url(r'^transacciones/', include('Transacciones.urls', namespace='Transacciones')),
    url(r'^registro/','Usuario.views.registro', name='registro'),
    url(r'^empresa/',include('Comodin.urls', namespace='index')),
    url(r'^finanzas/','Planillas.views.finanzas', name= 'finanzas'),
    # url(r'^clientes/$','Comodin.views.clientes', name='clientes'),
    url(r'^marca/',MarcaCreate.as_view(), name = 'marca'),
    url(r'^filtro/',filtroP,name = 'filtroP'),
    url(r'^productos/', include('Producto.urls', namespace= 'Producto')),
    url(r'^trans/','Transacciones.views.trans',name="trans"),
    url(r'^$','Usuario.views.inicio',name="base"),
    url(r'^logout/$', 'Usuario.views.cerrar', name='cerrar'),
    url(r'^filtro_m/$', 'Localizaciones.views.BusquedaMunicipio', name='filtro_municipio')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else:
    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

src/Transacciones/forms.py
from django import forms
from django.utils import timezone

from .models import Factura,DetalleFactura,Recibo,Abonos,Credito

class FacturaForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = [
        "serie",
        "noDocumento",
        "precioTotal",
        "anulada",
        "Comodin_id",
        ]

class DetalleFacturaForm(forms.ModelForm):
    class Meta:
        model = DetalleFactura
        fields = [
        "Factura_id",
        "Producto_id",
        "subTotal",
        "cantidad",
        ]

class ReciboForm(forms.ModelForm):
    class Meta:
        model = Recibo
        fields = [
        "noDocumento",
        ]

class AbonosForm(forms.ModelForm):
    class Meta:
        model = Abonos
        fields = [
        "monto"
        ]

class CreditoForm(forms.ModelForm):
    class Meta:
        model = Credito
        fields = [
        "monto",
        "saldo",
        "fechaLimite",
        "fechaAprobacion",
        ]

        # def __init__(self, *args, **kwargs):
        #     super(CreditoForm, self).__init__(*args, **kwargs)
        #
        #     self.fields['fechaLimite'].widget = forms.Textarea(
        #         attrs = {
        #             'placeholder': str(timezone.now())
        #         }
        #     )
        #
        #     self.fields['fechaAprobacion'].widget = forms.Textarea(
        #         attrs = {
        #             'placeholder': str(timezone.now())
        #         }
        #     )

src/Transacciones/views.py
#encoding: utf-8

import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Sum
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.contrib import messages

from  Transacciones.models import Factura,Recibo
from Comodin.models import Marca, Comodin
from Producto.models import Tipo_Producto, Producto , Lote
from Agencia.models import Mercaderia
from .models import Factura, DetalleFactura, Credito, Abonos
from .forms import ReciboForm,AbonosForm,FacturaForm,DetalleFacturaForm,CreditoForm

@login_required(login_url='base')
def recibo(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    form = ReciboForm(request.POST or None)
    context = {
        "form":form,
    }

    if form.is_valid():
        form.save()

    return render(request, 'recibo.html', context)

@login_required(login_url='base')
def abonos(request, tipo):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    if tipo == 'compras':
        creditos=Credito.objects.filter(Factura_id__Comodin_id__tipo=1)
    else:
        creditos=Credito.objects.filter(Factura_id__Comodin_id__tipo=0)

    creditos = creditos.filter(finalizado=0)
    form = AbonosForm(request.POST or None)
    context={
        "form":form,
        "creditos": creditos
    }
    if form.is_valid():
        form.save(commit=False)
        credito = Credito.objects.get(id=request.POST['creditos'])

        monto = form.cleaned_data.get('monto')

        if monto > credito.saldo:
            messages.error(request,
                'El monto es mayor que el saldo del credito, Saldo:'+str(credito.saldo))
        else:
            credito.saldo -= monto

            if credito.saldo == 0:
                print 'monto 0'
                credito.finalizado = 1
            credito.save()
            credito.Factura_id.Comodin_id.saldo = credito.Factura_id.Comodin_id.saldo - monto
            credito.Factura_id.Comodin_id.save()
            abono = Abonos.objects.create(
                monto=monto,
                Credito_id=credito
            )

            if tipo=='compras':
                return HttpResponseRedirect('/transacciones/compras/abonos')
            else:
                return HttpResponseRedirect('/transacciones/ventas/abonos')

    return render(request, 'transacciones/abonos.html', context)

@login_required(login_url='base')
def abonosList(request, tipo):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')

    if tipo == 'compras':
        abonos = Abonos.objects.filter(
            Credito_id__Factura_id__Comodin_id__tipo = 1
        )
    else:
        abonos = Abonos.objects.filter(
            Credito_id__Factura_id__Comodin_id__tipo = 0
        )

    context = {
        'abonos': abonos,
    }

    return render(request, 'transacciones/abonos_list.html', context)

class AbonoDetail(DetailView):
    model = Abonos
    template_name = 'transacciones/abono_detail.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect('/')
        return super(AbonoDetail, self).dispatch(request, *args, **kwargs)

@login_required(login_url='base')
def factura(request):

    #usuario = request.user

    form = FacturaForm(request.POST or None)
    form2 = DetalleFacturaForm(request.POST or None)
    datos = Factura.objects.all()
    context = {
        "form" : form,
        "form2" : form2,
        "datos" : datos,
    }
    if form.is_valid():
        form.save()
    if form2.is_valid():
        form2.save()
    return render(request,'factura.html',context)

@login_required(login_url='base')
def detalleFactura(request):
    form = DetalleFacturaForm(request.POST or None)
    context = {
        "form":form,
    }
    if form.is_valid():
        form.save()
    return render(request,'detalleFactura.html',context)

@login_required(login_url='base')
def credito(request):
    print timezone.now()
    if request.GET:
        factura = request.GET['factura']

        try:
            factura = Factura.objects.get(id=factura)

            try:
                credito = Credito.objects.get(Factura_id=factura)
                print 'try'
            except Credito.DoesNotExist:
                print str(timezone.now())

                form = CreditoForm(request.POST or None)

                context = {
                    "form":form,
                    }

                if form.is_valid():
                    print 'form'

                    form.save(commit=False)

                    credito = Credito.objects.create(
                        aprobado = True,
                        monto = form.cleaned_data["monto"],
                        saldo = form.cleaned_data["saldo"],
                        finalizado = False,
                        fechaLimite = form.cleaned_data["fechaLimite"],
                        fechaAprobacion = form.cleaned_data["fechaAprobacion"],
                        Usuario_id = request.user,
                        Factura_id = factura
                    )


                    factura.Comodin_id.saldo = factura.Comodin_id.saldo + credito.saldo
                    factura.Comodin_id.save()

                    credito.save()



                    messages.info(request,
                        'Credito creado: ' + str(credito.id))
                    return HttpResponseRedirect('/transacciones/')

                return render(request,'transacciones/credito.html',context)

            messages.error(request,
                'Esa factura ya tiene un credito.')
            return HttpResponseRedirect('/transacciones/')

        except Factura.DoesNotExist:
            messages.error(request,
                'No existe esa factura.')
            return HttpResponseRedirect('/transacciones/')

    messages.error(request,
        'Ocurrió un error.')
    return HttpResponseRedirect('/transacciones/')

@login_required(login_url='base')
def trans(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/')
    datos = Factura.objects.all()
    return render(request,'base.html',{"datos":datos})

@login_required(login_url='base')
def ventas(request):

    context = {
        'tipos': Tipo_Producto.objects.all(),
        'marcas': Marca.objects.all(),
        'clientes': Comodin.objects.filter(tipo=0),
        'noDoc': Factura.objects.filter(Comodin_id__tipo=0).count() + 1
    }

    return render(request, 'transacciones/ventas.html', context)

@login_required(login_url='base')
def compras(request):

    context = {
        'tipos': Tipo_Producto.objects.all(),
        'marcas': Marca.objects.all(),
        'proveedores': Comodin.objects.filter(tipo=1)
    }

    return render(request, 'transacciones/compras.html', context)

@login_required(login_url='base')
def venta(request):
    detalles = request.GET['detalles']
    cliente = request.GET['cliente']
    numDoc = request.GET['num_doc']

    comodin = Comodin.objects.get(id=cliente)
    factura = Factura.objects.create(
                serie='A',
                noDocumento=numDoc,
                anulada=False,
                Comodin_id=comodin
                )

    factura.save()

    data = json.loads(detalles)

    agencia = request.user.Empleado_id.Agencia_id

    total = 0
    for majorkey, subdict in data.iteritems():
        detalle = DetalleFactura()
        for subkey, value in subdict.iteritems():
            if subkey == 'cantidad':
                detalle.cantidad = value
            elif subkey == 'descripcion':
                producto = Producto.objects.get(id=value)
                detalle.Producto_id = producto
            elif subkey == 'subtotal':
                total += value
                detalle.subTotal = value


        mercaderia = Mercaderia.objects.get(
                            Agencia_id=agencia,
                            Producto_id=detalle.Producto_id
                            )

        mercaderia.cantidad -= detalle.cantidad

        mercaderia.save()
        detalle.Factura_id = factura
        detalle.save()

    factura.precioTotal = total
    factura.save()


    agencia.capital += factura.precioTotal
    agencia.save()


    factura = Factura.objects.filter(id = factura.id)


    data = serializers.serialize('json', factura)

    return HttpResponse(data, content_type='application/json')

@login_required(login_url='base')
def compra(request):
    detalles = request.GET['detalles']
    proveedor = request.GET['proveedor']
    serie = request.GET['serie']
    numDoc = request.GET['num_doc']


    comodin = Comodin.objects.get(id=proveedor)
    factura = Factura.objects.create(
                serie=serie,
                noDocumento=numDoc,
                anulada=False,
                Comodin_id=comodin
                )

    factura.save()

    data = json.loads(detalles)

    agencia = request.user.Empleado_id.Agencia_id

    total = 0
    for majorkey, subdict in data.iteritems():
        detalle = DetalleFactura()
        for subkey, value in subdict.iteritems():
            if subkey == 'cantidad':
                detalle.cantidad = value
            elif subkey == 'descripcion':
                producto = Producto.objects.get(id=value)
                detalle.Producto_id = producto
            elif subkey == 'subtotal':
                total += value
                detalle.subTotal = value

        try:
            mercaderia = Mercaderia.objects.get(
                            Agencia_id=agencia,
                            Producto_id=detalle.Producto_id

src/templates/transacciones/abonos_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Abonos</h2>
</br>

<div class="listados">

  <table id="tblDatos" class="table">
    <tr>
      <th>ID</th>
      <th>Cliente</th>
      <th>Fecha</th>
      <th>Factura</th>
      <th>Credito</th>
    </tr>
    {% for abono in abonos %}
    <tr>
      <td>
        {{abono.id}}
      </td>
      <td>
        {{abono.Credito_id.Factura_id.Comodin_id}}
      </td>
      <td>
        {{abono.fecha}}
      </td>
      <td>
        {{abono.Credito_id.Factura_id}}
      </td>
      <td>
        {{abono.Credito_id}}
      </td>
      <td>
        <a href={% url 'Transacciones:abonos_detail' abono.id %}>Ver</a>
        <!-- |
        <a href="#">Editar</a> -->
      </td>
    </tr>
    {% endfor %}
  </table>

</div>

</table>
<div id="paginador"></div>

</div>

{% endblock %}


{% block js %}
<script type="text/javascript">
var p = new Paginador(
  document.getElementById('paginador'),
  document.getElementById('tblDatos'),
  10
);

p.Mostrar();
</script>
{% endblock %}

src/templates/transacciones/compras.html
{% extends 'base.html' %}

{% block content %}

<div class = "camposForms">

  <div class="tboxs">
      <label>Proveedor:</label>
      {% csrf_token %}
        <select id="proveedor" name="proveedor">
        <option selected>------</option>
        {% for proveedor in proveedores %}
          <option value="{{proveedor.id}}">{{proveedor}}</option>
          {% endfor %}
        </select>

          <a href={% url 'index:comodinCreate' %} class = "lnk" target="_blank">+</a>

        <br></br>
        <label>Serie Factura:</label>
        <input type="text" id="serie" name="serie" value="A">
        <br></br>
        <label>No. Factura:</label>
        <input type="text" id="num" name="num" value="0000" unique = True>
  </div>

<hr>
<div class = "tbox1">
  <form action="" method="post" onsubmit="return validacion()">
    {% csrf_token %}
    <label>Tipo de Producto</label>
    <select id="tipo" name="tipo1">
      <option selected>------</option>
      {% for tipo in tipos %}
        <option value="{{tipo.id}}">{{tipo}}</option>
      {% endfor %}
    </select></br>
    <label>Marca</label>
    <select id="marca" name="marca">
      <option selected>------</option>
      {% for marca in marcas %}
        <option value="{{marca.id}}">{{marca}}</option>
      {% endfor %}
    </select></br>
    <label>Producto</label>
    <select id='productos' name='productos1'>
      <option selected>------</option>
      <!-- {% for producto in productos %}
        <option value="{{producto.id}}">{{producto.nombre}}</option>
      {% endfor %} -->
    </select></br>
    <label>Cantidad</label>
    <input id="cantidad" type="number" name="cantidad" value=0 min="0"></br>
    <label>Precio</label>
    <input id="precio" type="text" name="precio" value=0></br>
    <label>Crédito</label>
    <input type="checkbox" id="credito" name="credito" checked></br>
    <input id="agregar" type="button" value="Agregar detalle"></br>
  </form>
</div>

</div>

<div class = "tbox2">
  <table class="table" id='detalles' name="detalles">
    <tr>
      <td>Cantidad</td>
      <td width=50%>Descripción</td>
      <td>Precio unitario</td>
      <td>Sub-Total</td>
    </tr>
  </table>
  <input id="facturar" type="button" value="Facturar"></br>
</div>

{% endblock %}

{% block js %}
{% csrf_token %}
<script type="text/javascript">
  $('#agregar').on('click', agregarDetalle);
  $('#marca').on('change', busquedaProducto);
  $('#facturar').on('click',facturar);

  //$('#credito').on('change',function(){
    //alert(document.getElementById('credito').checked)
  //})

  function facturar(){

    var filas = document.getElementById('detalles').rows;
    var total = 0;

    var detalles = '{\n';

    for(var i=1; i<filas.length;i++){
      var detalle = '\n"detalle'+i+'":'+'{'+
        '\n\t"cantidad":' + filas[i].cells[0].innerHTML +','+
        '\n\t"descripcion":' + filas[i].cells[1].id +','+
        '\n\t"subtotal":' + filas[i].cells[3].innerHTML;
        total = total + parseFloat(filas[i].cells[3].innerHTML);
      if (i==filas.length-1){
        detalle += '\n\t}\n';
      }else{
        detalle += '\n\t}, \n';
      }

      detalles = detalles + detalle;
      //console.log(detalle);
    }

    detalles = detalles + '}';
    console.log(total);

    //var json = JSON.parse(detalles);

    $.ajax({

      data: {
        'detalles': detalles,
        'proveedor': $('#proveedor').val(),
        'serie': $('#serie').val(),
        'num_doc': $('#num').val()
      },
      url: "{% url 'Transacciones:compra' %}",
      type: 'get',
      dataType: 'json',
      success: function(data){
        alert("Factura creada con exito.");

        if(!document.getElementById('credito').checked)
          location.href += 'facturas/';
        else
          location.href = location.href + 'crear_credito/?factura='+data[0].pk+'&monto='+total;
      }
    });

  }

  function agregarDetalle(){

    var tabla = document.getElementById('detalles');
    var cantidad = $('#cantidad').val();
    var combo = document.getElementById('productos');
    var producto = combo.options[combo.selectedIndex].text;
    var precio = $('#precio').val();

    if(cantidad <= 0 || precio<0){
      alert("Ingrese valores positivos en los campos Precio y Cantidad");
      return;
    }

    var fila = document.createElement('tr');
    var columna = document.createElement("td");

    var texto = document.createTextNode(cantidad);
    var columna = document.createElement("td");
      columna.appendChild(texto);
      fila.appendChild(columna);

    texto = document.createTextNode(producto);
    var columna = document.createElement("td");
      columna.appendChild(texto);
      columna.id = $('#productos').val();
      fila.appendChild(columna);

    texto = document.createTextNode(precio);
    var columna = document.createElement("td");
      columna.appendChild(texto);
      fila.appendChild(columna);

    var subtotal = cantidad * precio;

    texto = document.createTextNode(subtotal);
    var columna = document.createElement("td");
      columna.appendChild(texto);
      fila.appendChild(columna);

    tabla.appendChild(fila);

    console.log(document.getElementById('credito').checked);

    document.getElementById('tipo').options[0].selected = true;
    document.getElementById('marca').options[0].selected = true;
    document.getElementById('productos').options[0].selected = true;

  }



  function busquedaProducto(){
    var id_marca = $(this).val();
    var id_tipo = $('#tipo').val();

    $.ajax({

      data: {
        'id_marca':id_marca,
        'id_tipo' : id_tipo
      },
      url: "{% url 'Producto:filtroProducto' %}",
      type: 'get',
      success: function(data){
        var inner = document.getElementById('productos');

        inner.innerHTML = "";

        for(var i=0; i<data.length;i++){
          var nuevo = document.createElement("option");

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.descripcion + "-"
                            + data[i].fields.Material_id + "-"
                            + data[i].fields.Calibre_id + "-"
                            + data[i].fields.Forma_id + "-"
                            + data[i].fields.Longitud_id;

          inner.options.add(nuevo);
        }

      }

    })

  }


</script>
{% endblock %}

src/templates/transacciones/credito_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Creditos de {{mensaje}}</h2>
</br>

<div class = "listados">


  <table id='tblDatos' class = "table">
    <tr>
      <td><strong>Credito</td>
      <td><strong>Usuario</td>
      <td><strong>Finalizado</td>
      <td><strong>Fecha Limite</td>
      <td><strong>Saldo</td>
      <td><strong>Monto</td>
    </tr>
    {% for credito in creditos %}
    {% if credito.finalizado %}
    <tr>
      <td bgcolor="#F5A9A9">
        {{credito.credito_name}}
      </td>
      <td bgcolor="#F5A9A9">
        {{credito.Usuario_id}}
      </td>
      <td bgcolor="#F5A9A9">
        {% if credito.finalizado %}
        Si
        {% else %}
        No
        {% endif %}
      </td>
      <td bgcolor="#F5A9A9">
        {{credito.fechaLimite}}
      </td>
      <td bgcolor="#F5A9A9">
        {{credito.saldo}}
      </td>
      <td bgcolor="#F5A9A9">
        {{credito.monto}}
      </td>
      {% if credito.Factura_id.Comodin_id.tipo %}
      <td bgcolor="#F5A9A9">
        <a href={% url 'Transacciones:creditoPDetail' credito.id %}>Ver</a>
      </td>
      {% else %}
      <td bgcolor="#F5A9A9">
        <a href={% url 'Transacciones:creditoCDetail' credito.id %}>Ver</a>
      </td>
      {% endif %}
    </tr>
    {% else %}
    <tr>
      <td>
        {{credito.credito_name}}
      </td>
      <td>
        {{credito.Usuario_id}}
      </td>
      <td>
        {% if credito.finalizado %}
        Si
        {% else %}
        No
        {% endif %}
      </td>
      <td>
        {{credito.fechaLimite}}
      </td>
      <td>
        {{credito.saldo}}
      </td>
      <td>
        {{credito.monto}}
      </td>
      {% if credito.Factura_id.Comodin_id.tipo %}
      <td>
        <a href={% url 'Transacciones:creditoPDetail' credito.id %}>Ver</a>
      </td>
      {% else %}
      <td>
        <a href={% url 'Transacciones:creditoCDetail' credito.id %}>Ver</a>
      </td>
      {% endif %}
    </tr>
    {% endif %}
    {% endfor %}

  </table>
  <div id="paginador"></div>

</div>

{% endblock %}


{% block js %}
<script type="text/javascript">
  var p = new Paginador(
    document.getElementById('paginador'),
    document.getElementById('tblDatos'),
    10
  );

  p.Mostrar();
</script>
{% endblock %}

src/templates/transacciones/home.html
{% extends 'base.html' %}


{% block content %}



{% endblock %}

src/templates/transacciones/transacciones.html
{% extends 'base.html' %}

{% block content %}

<h2>Transacciones</h2>
<br/>

<div class="messages">
  {% if messages %}
    {% for message in messages %}
    <label>{{message}}</label>
    {% endfor %}
  {% endif %}
</div>

<div class = "submenu">


  <table class = "table">
  <tr>
    <td><strong>Compras</td>
    <td><a href= "/transacciones/compras"><i>Crear</i></a></td>
    <td><a href= "/transacciones/compras/facturas"><i>Desplegar</i></a></td>
  </tr>

  <tr>
    <td><strong>Ventas</td>
    <td><a href= "/transacciones/ventas"><i>Crear</i></a></td>
    <td><a href= "/transacciones/ventas/facturas"><i>Desplegar</i></a></td>
  </tr>

  <tr>
    <td><strong>Créditos Compras</td>
    <td><a href= "/"><i></i></a></td>
    <td><a href= "/transacciones/compras/creditos"><i>Desplegar</i></a></td>
  </tr>


  <tr>
    <td><strong>Créditos Ventas</td>
    <td><a href= "/"><i></i></a></td>
    <td><a href= "/transacciones/ventas/creditos"><i>Desplegar</i></a></td>
  </tr>

  <tr>
    <td><strong>Abonos Compras</td>
    <td><a href= {% url 'Transacciones:abonos' 'compras' %}><i>Crear</i></a></td>
    <td><a href= {% url 'Transacciones:abonos_list' 'compras'%}><i>Desplegar</i></a></td>
  </tr>

  <tr>
    <td><strong>Abonos Ventas</td>
    <td><a href= {% url 'Transacciones:abonos_v' 'ventas' %}><i>Crear</i></a></td>
    <td><a href= {% url 'Transacciones:abonos_list_v' 'ventas' %}><i>Desplegar</i></a></td>
  </tr>

  </table>



</div>
{% endblock %}